/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "on-tertiary": "#ffffff",
              "tertiary-fixed": "#d3e4fe",
              "inverse-on-surface": "#eff1f3",
              "on-secondary-fixed-variant": "#004395",
              "outline": "#76777d",
              "surface-container": "#1e2124",
              "on-background": "#f7f9fb",
              "surface-tint": "#bec6e0",
              "outline-variant": "#45464d",
              "tertiary-container": "#0b1c30",
              "on-tertiary-container": "#75859d",
              "surface-container-high": "#2d3133",
              "surface-dim": "#191c1e",
              "primary-fixed": "#dae2fd",
              "primary": "#ffffff",
              "on-error-container": "#ffdad6",
              "on-primary-container": "#dae2fd",
              "inverse-surface": "#f7f9fb",
              "tertiary-fixed-dim": "#b7c8e1",
              "on-error": "#690005",
              "secondary-fixed-dim": "#adc6ff",
              "surface-container-highest": "#333739",
              "surface-container-lowest": "#0f1113",
              "on-primary-fixed-variant": "#3f465c",
              "tertiary": "#ffffff",
              "surface-container-low": "#191c1e",
              "on-surface-variant": "#c6c6cd",
              "error-container": "#93000a",
              "on-tertiary-fixed": "#d3e4fe",
              "secondary": "#adc6ff",
              "primary-container": "#3f465c",
              "background": "#0f1113",
              "on-surface": "#f7f9fb",
              "on-primary-fixed": "#131b2e",
              "on-primary": "#131b2e",
              "error": "#ffb4ab",
              "surface": "#0f1113",
              "surface-variant": "#45464d",
              "secondary-fixed": "#d8e2ff",
              "on-secondary-fixed": "#001a42",
              "on-tertiary-fixed-variant": "#38485d",
              "surface-bright": "#333739",
              "on-secondary-container": "#d8e2ff",
              "inverse-primary": "#565e74",
              "on-secondary": "#002d64",
              "primary-fixed-dim": "#bec6e0",
              "secondary-container": "#004395"
      },
      "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
      },
      "spacing": {
              "md": "16px",
              "gutter": "24px",
              "margin": "32px",
              "xs": "4px",
              "xl": "48px",
              "base": "4px",
              "lg": "24px",
              "sm": "8px"
      },
      "fontFamily": {
              "body-md": ["Inter"],
              "data-mono": ["Inter"],
              "label-md": ["Inter"],
              "body-lg": ["Inter"],
              "headline-md": ["Manrope"],
              "headline-xl": ["Manrope"],
              "headline-lg": ["Manrope"]
      }
    },
  },
  plugins: [],
}
